### ISSUE TITLE
API/Sessions Route - Maintain session

### ISSUE THREAD

**Issue by ebnhawk** [grace-hopper-bazaar/bazaar-web#46]
Cart should... 
...refresh the page and have the cart persist, so that I don't lose my work (you may use sessionStorage, localStorage, cookies or JWT for this)

**Comment by cds-amal** [comment]
This overlaps with #43 
This logic belongs in the routes interface for the Cart model. 
There is a need for a LineItem, and Order Models as well

Cart hasMany LineItem
LineItem belongsTo Cart
LineItem belongsTo Order

Order belongsTo User
User hasMany Order
Order hasMany LineItem
