### ISSUE TITLE
Add Google OAuth2 support

### ISSUE THREAD

**Issue by cds-amal** [grace-hopper-bazaar/bazaar-web#64]
Enable login via Google OAuth2

1. Create new app at: https://console.developers.google.com/
    make sure to enable Google+ (right?!?)
    set up authentication with callback earl: http://localhost/auth/google/callback
    SECURELY store secrets. 

2. Display button handle click/submit to /auth/google

3. will have to put the secrets into the environment as GOOGLE_CLIENT_ID && GOOGLE_CLIENT_SECRET 

4. will have to set these secrets on heroku as well

**Comment by ebnhawk** [comment]
Client ID and client secret stored in Heroku.
